/**
 * Autogenerated by Thrift Compiler (0.7.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Text;
using Thrift.Protocol;

namespace Thrift.HBase
{
    [Serializable]
    public class TRegionInfo : TBase
    {
        public Isset __isset;
        private byte[] _endKey;
        private long _id;
        private byte[] _name;
        private byte[] _startKey;
        private byte _version;

        public byte[] StartKey
        {
            get { return this._startKey; }
            set
            {
                this.__isset.startKey = true;
                this._startKey = value;
            }
        }

        public byte[] EndKey
        {
            get { return this._endKey; }
            set
            {
                this.__isset.endKey = true;
                this._endKey = value;
            }
        }

        public long Id
        {
            get { return this._id; }
            set
            {
                this.__isset.id = true;
                this._id = value;
            }
        }

        public byte[] Name
        {
            get { return this._name; }
            set
            {
                this.__isset.name = true;
                this._name = value;
            }
        }

        public byte Version
        {
            get { return this._version; }
            set
            {
                this.__isset.version = true;
                this._version = value;
            }
        }

        #region TBase Members

        public void Read(TProtocol iprot)
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.String)
                        {
                            this.StartKey = iprot.ReadBinary();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 2:
                        if (field.Type == TType.String)
                        {
                            this.EndKey = iprot.ReadBinary();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 3:
                        if (field.Type == TType.I64)
                        {
                            this.Id = iprot.ReadI64();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 4:
                        if (field.Type == TType.String)
                        {
                            this.Name = iprot.ReadBinary();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 5:
                        if (field.Type == TType.Byte)
                        {
                            this.Version = iprot.ReadByte();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }

        public void Write(TProtocol oprot)
        {
            var struc = new TStruct("TRegionInfo");
            oprot.WriteStructBegin(struc);
            var field = new TField();
            if (this.StartKey != null && this.__isset.startKey)
            {
                field.Name = "startKey";
                field.Type = TType.String;
                field.ID = 1;
                oprot.WriteFieldBegin(field);
                oprot.WriteBinary(this.StartKey);
                oprot.WriteFieldEnd();
            }
            if (this.EndKey != null && this.__isset.endKey)
            {
                field.Name = "endKey";
                field.Type = TType.String;
                field.ID = 2;
                oprot.WriteFieldBegin(field);
                oprot.WriteBinary(this.EndKey);
                oprot.WriteFieldEnd();
            }
            if (this.__isset.id)
            {
                field.Name = "id";
                field.Type = TType.I64;
                field.ID = 3;
                oprot.WriteFieldBegin(field);
                oprot.WriteI64(this.Id);
                oprot.WriteFieldEnd();
            }
            if (this.Name != null && this.__isset.name)
            {
                field.Name = "name";
                field.Type = TType.String;
                field.ID = 4;
                oprot.WriteFieldBegin(field);
                oprot.WriteBinary(this.Name);
                oprot.WriteFieldEnd();
            }
            if (this.__isset.version)
            {
                field.Name = "version";
                field.Type = TType.Byte;
                field.ID = 5;
                oprot.WriteFieldBegin(field);
                oprot.WriteByte(this.Version);
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        #endregion

        public override string ToString()
        {
            var sb = new StringBuilder("TRegionInfo(");
            sb.Append("StartKey: ");
            sb.Append(this.StartKey);
            sb.Append(",EndKey: ");
            sb.Append(this.EndKey);
            sb.Append(",Id: ");
            sb.Append(this.Id);
            sb.Append(",Name: ");
            sb.Append(this.Name);
            sb.Append(",Version: ");
            sb.Append(this.Version);
            sb.Append(")");
            return sb.ToString();
        }

        #region Nested type: Isset

        [Serializable]
        public struct Isset
        {
            public bool endKey;
            public bool id;
            public bool name;
            public bool startKey;
            public bool version;
        }

        #endregion
    }
}