/**
 * Autogenerated by Thrift Compiler (0.7.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Thrift.HBase
{
    [Serializable]
    public class TRowResult : TBase
    {
        public Isset __isset;
        private Dictionary<byte[], TCell> _columns;
        private byte[] _row;

        public byte[] Row
        {
            get { return this._row; }
            set
            {
                this.__isset.row = true;
                this._row = value;
            }
        }

        public Dictionary<byte[], TCell> Columns
        {
            get { return this._columns; }
            set
            {
                this.__isset.columns = true;
                this._columns = value;
            }
        }

        #region TBase Members

        public void Read(TProtocol iprot)
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.String)
                        {
                            this.Row = iprot.ReadBinary();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 2:
                        if (field.Type == TType.Map)
                        {
                            {
                                this.Columns = new Dictionary<byte[], TCell>();
                                TMap _map4 = iprot.ReadMapBegin();
                                for (int _i5 = 0; _i5 < _map4.Count; ++_i5)
                                {
                                    byte[] _key6;
                                    TCell _val7;
                                    _key6 = iprot.ReadBinary();
                                    _val7 = new TCell();
                                    _val7.Read(iprot);
                                    this.Columns[_key6] = _val7;
                                }
                                iprot.ReadMapEnd();
                            }
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }

        public void Write(TProtocol oprot)
        {
            var struc = new TStruct("TRowResult");
            oprot.WriteStructBegin(struc);
            var field = new TField();
            if (this.Row != null && this.__isset.row)
            {
                field.Name = "row";
                field.Type = TType.String;
                field.ID = 1;
                oprot.WriteFieldBegin(field);
                oprot.WriteBinary(this.Row);
                oprot.WriteFieldEnd();
            }
            if (this.Columns != null && this.__isset.columns)
            {
                field.Name = "columns";
                field.Type = TType.Map;
                field.ID = 2;
                oprot.WriteFieldBegin(field);
                {
                    oprot.WriteMapBegin(new TMap(TType.String, TType.Struct, this.Columns.Count));
                    foreach (var _iter8 in this.Columns.Keys)
                    {
                        oprot.WriteBinary(_iter8);
                        this.Columns[_iter8].Write(oprot);
                    }
                    oprot.WriteMapEnd();
                }
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        #endregion

        public override string ToString()
        {
            var sb = new StringBuilder("TRowResult(");
            sb.Append("Row: ");
            sb.Append(this.Row);
            sb.Append(",Columns: ");
            sb.Append(this.Columns);
            sb.Append(")");
            return sb.ToString();
        }

        #region Nested type: Isset

        [Serializable]
        public struct Isset
        {
            public bool columns;
            public bool row;
        }

        #endregion
    }
}